name: tbpor-env
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - freetype=2.10.4
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - libffi=3.4.2
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.1.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.4
  - pytorch=1.12.0
  - pytorch-mutex=1.0=cuda
  - requests=2.28.1
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - typing_extensions
  - tzdata=2022a
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - asttokens==2.0.5
    - backcall==0.2.0
    - blis==0.7.8
    - catalogue==2.0.7
    - click==8.1.3
    - colorama==0.4.5
    - cvxopt==1.3.0
    - cycler==0.11.0
    - cymem==2.0.6
    - decorator==5.1.1
    - deprecation==2.1.0
    - executing==0.8.3
    - fonttools==4.34.4
    - intervaltree==3.1.0
    - ipython==8.4.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonpickle==2.2.0
    - kiwisolver==1.4.3
    - langcodes==3.3.0
    - lxml==4.9.1
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mpmath==1.2.1
    - murmurhash==1.0.7
    - networkx==2.8.4
    - packaging==21.3
    - pandas==1.4.3
    - parso==0.8.3
    - pathy==0.6.2
    - pickleshare==0.7.5
    - pm4py==2.2.24
    - preshed==3.0.6
    - prompt-toolkit==3.0.30
    - pure-eval==0.2.2
    - pydantic==1.9.1
    - pydotplus==2.0.2
    - pygments==2.12.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyvis==0.2.1
    - scipy==1.8.1
    - smart-open==5.2.1
    - sortedcontainers==2.4.0
    - spacy==3.4.0
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.3
    - srsly==2.4.3
    - stack-data==0.3.0
    - stringdist==1.0.9
    - sympy==1.10.1
    - thinc==8.1.0
    - tqdm==4.64.0
    - traitlets==5.3.0
    - typer==0.4.2
    - wasabi==0.9.1
    - wcwidth==0.2.5

